# Generated by Django 3.0.7 on 2020-06-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
